-- Catálogo de marcas y modelos (autos, SUV, pickups y utilitarios del mercado argentino).
-- Migración repetible: Flyway la vuelve a correr cada vez que cambia este archivo.
-- Solo agrega: ON CONFLICT DO NOTHING evita duplicados y nunca se borra nada desde acá.
-- Para sumar un modelo, agregá una fila en el bloque de su marca. Para una marca nueva, sumala también arriba.
-- Los slugs van en minúsculas, sin acentos y con guiones.

INSERT INTO marca (nombre, slug) VALUES
    ('Alfa Romeo', 'alfa-romeo'),
    ('Audi', 'audi'),
    ('BMW', 'bmw'),
    ('BYD', 'byd'),
    ('Chery', 'chery'),
    ('Chevrolet', 'chevrolet'),
    ('Citroën', 'citroen'),
    ('DS', 'ds'),
    ('Fiat', 'fiat'),
    ('Ford', 'ford'),
    ('Haval', 'haval'),
    ('Honda', 'honda'),
    ('Hyundai', 'hyundai'),
    ('Iveco', 'iveco'),
    ('Jeep', 'jeep'),
    ('Kia', 'kia'),
    ('Land Rover', 'land-rover'),
    ('Mercedes-Benz', 'mercedes-benz'),
    ('Mini', 'mini'),
    ('Mitsubishi', 'mitsubishi'),
    ('Nissan', 'nissan'),
    ('Peugeot', 'peugeot'),
    ('Porsche', 'porsche'),
    ('Ram', 'ram'),
    ('Renault', 'renault'),
    ('Subaru', 'subaru'),
    ('Suzuki', 'suzuki'),
    ('Toyota', 'toyota'),
    ('Volkswagen', 'volkswagen'),
    ('Volvo', 'volvo')
ON CONFLICT DO NOTHING;

INSERT INTO modelo (marca_id, nombre, slug)
SELECT marca.id, v.nombre, v.slug
FROM (VALUES
    -- Alfa Romeo
    ('alfa-romeo', 'Giulietta', 'giulietta'),
    ('alfa-romeo', 'Giulia', 'giulia'),
    ('alfa-romeo', 'MiTo', 'mito'),
    ('alfa-romeo', 'Stelvio', 'stelvio'),
    ('alfa-romeo', 'Tonale', 'tonale'),
    -- Audi
    ('audi', 'A1', 'a1'),
    ('audi', 'A3', 'a3'),
    ('audi', 'A4', 'a4'),
    ('audi', 'A5', 'a5'),
    ('audi', 'A6', 'a6'),
    ('audi', 'Q2', 'q2'),
    ('audi', 'Q3', 'q3'),
    ('audi', 'Q5', 'q5'),
    ('audi', 'Q7', 'q7'),
    ('audi', 'Q8', 'q8'),
    ('audi', 'TT', 'tt'),
    -- BMW
    ('bmw', 'Serie 1', 'serie-1'),
    ('bmw', 'Serie 2', 'serie-2'),
    ('bmw', 'Serie 3', 'serie-3'),
    ('bmw', 'Serie 4', 'serie-4'),
    ('bmw', 'Serie 5', 'serie-5'),
    ('bmw', 'X1', 'x1'),
    ('bmw', 'X2', 'x2'),
    ('bmw', 'X3', 'x3'),
    ('bmw', 'X4', 'x4'),
    ('bmw', 'X5', 'x5'),
    ('bmw', 'X6', 'x6'),
    -- BYD
    ('byd', 'Dolphin Mini', 'dolphin-mini'),
    ('byd', 'Dolphin', 'dolphin'),
    ('byd', 'Seal', 'seal'),
    ('byd', 'Yuan Pro', 'yuan-pro'),
    ('byd', 'Yuan Plus', 'yuan-plus'),
    ('byd', 'Song Pro', 'song-pro'),
    -- Chery
    ('chery', 'QQ', 'qq'),
    ('chery', 'Fulwin', 'fulwin'),
    ('chery', 'Arrizo 5', 'arrizo-5'),
    ('chery', 'Tiggo 2', 'tiggo-2'),
    ('chery', 'Tiggo 3', 'tiggo-3'),
    ('chery', 'Tiggo 4', 'tiggo-4'),
    ('chery', 'Tiggo 5', 'tiggo-5'),
    ('chery', 'Tiggo 7', 'tiggo-7'),
    ('chery', 'Tiggo 8', 'tiggo-8'),
    -- Chevrolet
    ('chevrolet', 'Corsa', 'corsa'),
    ('chevrolet', 'Classic', 'classic'),
    ('chevrolet', 'Celta', 'celta'),
    ('chevrolet', 'Prisma', 'prisma'),
    ('chevrolet', 'Agile', 'agile'),
    ('chevrolet', 'Onix', 'onix'),
    ('chevrolet', 'Onix Plus', 'onix-plus'),
    ('chevrolet', 'Sonic', 'sonic'),
    ('chevrolet', 'Cobalt', 'cobalt'),
    ('chevrolet', 'Aveo', 'aveo'),
    ('chevrolet', 'Astra', 'astra'),
    ('chevrolet', 'Vectra', 'vectra'),
    ('chevrolet', 'Cruze', 'cruze'),
    ('chevrolet', 'Meriva', 'meriva'),
    ('chevrolet', 'Zafira', 'zafira'),
    ('chevrolet', 'Spin', 'spin'),
    ('chevrolet', 'Tracker', 'tracker'),
    ('chevrolet', 'Equinox', 'equinox'),
    ('chevrolet', 'Captiva', 'captiva'),
    ('chevrolet', 'Trailblazer', 'trailblazer'),
    ('chevrolet', 'S10', 's10'),
    ('chevrolet', 'Montana', 'montana'),
    ('chevrolet', 'Silverado', 'silverado'),
    ('chevrolet', 'Camaro', 'camaro'),
    -- Citroën
    ('citroen', 'C3', 'c3'),
    ('citroen', 'C3 Aircross', 'c3-aircross'),
    ('citroen', 'C4', 'c4'),
    ('citroen', 'C4 Lounge', 'c4-lounge'),
    ('citroen', 'C4 Cactus', 'c4-cactus'),
    ('citroen', 'C4 Picasso', 'c4-picasso'),
    ('citroen', 'C5 Aircross', 'c5-aircross'),
    ('citroen', 'C-Elysée', 'c-elysee'),
    ('citroen', 'Xsara Picasso', 'xsara-picasso'),
    ('citroen', 'Basalt', 'basalt'),
    ('citroen', 'Berlingo', 'berlingo'),
    ('citroen', 'Jumpy', 'jumpy'),
    ('citroen', 'Jumper', 'jumper'),
    -- DS
    ('ds', 'DS3', 'ds3'),
    ('ds', 'DS4', 'ds4'),
    ('ds', 'DS7', 'ds7'),
    -- Fiat
    ('fiat', 'Uno', 'uno'),
    ('fiat', 'Mobi', 'mobi'),
    ('fiat', 'Palio', 'palio'),
    ('fiat', 'Palio Weekend', 'palio-weekend'),
    ('fiat', 'Siena', 'siena'),
    ('fiat', 'Grand Siena', 'grand-siena'),
    ('fiat', 'Punto', 'punto'),
    ('fiat', 'Idea', 'idea'),
    ('fiat', 'Linea', 'linea'),
    ('fiat', 'Argo', 'argo'),
    ('fiat', 'Cronos', 'cronos'),
    ('fiat', '500', '500'),
    ('fiat', 'Pulse', 'pulse'),
    ('fiat', 'Fastback', 'fastback'),
    ('fiat', 'Strada', 'strada'),
    ('fiat', 'Toro', 'toro'),
    ('fiat', 'Titano', 'titano'),
    ('fiat', 'Fiorino', 'fiorino'),
    ('fiat', 'Doblò', 'doblo'),
    ('fiat', 'Ducato', 'ducato'),
    -- Ford
    ('ford', 'Ka', 'ka'),
    ('ford', 'Fiesta', 'fiesta'),
    ('ford', 'Focus', 'focus'),
    ('ford', 'Mondeo', 'mondeo'),
    ('ford', 'EcoSport', 'ecosport'),
    ('ford', 'Kuga', 'kuga'),
    ('ford', 'Territory', 'territory'),
    ('ford', 'Bronco Sport', 'bronco-sport'),
    ('ford', 'Bronco', 'bronco'),
    ('ford', 'Ranger', 'ranger'),
    ('ford', 'Maverick', 'maverick'),
    ('ford', 'F-150', 'f-150'),
    ('ford', 'Transit', 'transit'),
    ('ford', 'Mustang', 'mustang'),
    -- Haval
    ('haval', 'Jolion', 'jolion'),
    ('haval', 'H6', 'h6'),
    -- Honda
    ('honda', 'Fit', 'fit'),
    ('honda', 'City', 'city'),
    ('honda', 'Civic', 'civic'),
    ('honda', 'Accord', 'accord'),
    ('honda', 'WR-V', 'wr-v'),
    ('honda', 'HR-V', 'hr-v'),
    ('honda', 'ZR-V', 'zr-v'),
    ('honda', 'CR-V', 'cr-v'),
    -- Hyundai
    ('hyundai', 'i10', 'i10'),
    ('hyundai', 'Accent', 'accent'),
    ('hyundai', 'Elantra', 'elantra'),
    ('hyundai', 'i30', 'i30'),
    ('hyundai', 'Creta', 'creta'),
    ('hyundai', 'Kona', 'kona'),
    ('hyundai', 'Tucson', 'tucson'),
    ('hyundai', 'Santa Fe', 'santa-fe'),
    ('hyundai', 'H-1', 'h-1'),
    -- Iveco
    ('iveco', 'Daily', 'daily'),
    -- Jeep
    ('jeep', 'Renegade', 'renegade'),
    ('jeep', 'Compass', 'compass'),
    ('jeep', 'Commander', 'commander'),
    ('jeep', 'Cherokee', 'cherokee'),
    ('jeep', 'Grand Cherokee', 'grand-cherokee'),
    ('jeep', 'Wrangler', 'wrangler'),
    ('jeep', 'Gladiator', 'gladiator'),
    -- Kia
    ('kia', 'Picanto', 'picanto'),
    ('kia', 'Rio', 'rio'),
    ('kia', 'Cerato', 'cerato'),
    ('kia', 'Soul', 'soul'),
    ('kia', 'Seltos', 'seltos'),
    ('kia', 'Sportage', 'sportage'),
    ('kia', 'Sorento', 'sorento'),
    ('kia', 'Carnival', 'carnival'),
    -- Land Rover
    ('land-rover', 'Defender', 'defender'),
    ('land-rover', 'Discovery', 'discovery'),
    ('land-rover', 'Discovery Sport', 'discovery-sport'),
    ('land-rover', 'Range Rover Evoque', 'range-rover-evoque'),
    ('land-rover', 'Range Rover Velar', 'range-rover-velar'),
    ('land-rover', 'Range Rover Sport', 'range-rover-sport'),
    ('land-rover', 'Range Rover', 'range-rover'),
    -- Mercedes-Benz
    ('mercedes-benz', 'Clase A', 'clase-a'),
    ('mercedes-benz', 'Clase B', 'clase-b'),
    ('mercedes-benz', 'Clase C', 'clase-c'),
    ('mercedes-benz', 'Clase E', 'clase-e'),
    ('mercedes-benz', 'GLA', 'gla'),
    ('mercedes-benz', 'GLB', 'glb'),
    ('mercedes-benz', 'GLC', 'glc'),
    ('mercedes-benz', 'GLE', 'gle'),
    ('mercedes-benz', 'Clase X', 'clase-x'),
    ('mercedes-benz', 'Vito', 'vito'),
    ('mercedes-benz', 'Sprinter', 'sprinter'),
    -- Mini
    ('mini', 'Cooper', 'cooper'),
    ('mini', 'Countryman', 'countryman'),
    -- Mitsubishi
    ('mitsubishi', 'Lancer', 'lancer'),
    ('mitsubishi', 'ASX', 'asx'),
    ('mitsubishi', 'Outlander', 'outlander'),
    ('mitsubishi', 'Montero', 'montero'),
    ('mitsubishi', 'L200', 'l200'),
    -- Nissan
    ('nissan', 'March', 'march'),
    ('nissan', 'Note', 'note'),
    ('nissan', 'Tiida', 'tiida'),
    ('nissan', 'Versa', 'versa'),
    ('nissan', 'Sentra', 'sentra'),
    ('nissan', 'Kicks', 'kicks'),
    ('nissan', 'X-Trail', 'x-trail'),
    ('nissan', 'Murano', 'murano'),
    ('nissan', 'Frontier', 'frontier'),
    -- Peugeot
    ('peugeot', '206', '206'),
    ('peugeot', '207', '207'),
    ('peugeot', '208', '208'),
    ('peugeot', '301', '301'),
    ('peugeot', '307', '307'),
    ('peugeot', '308', '308'),
    ('peugeot', '408', '408'),
    ('peugeot', '2008', '2008'),
    ('peugeot', '3008', '3008'),
    ('peugeot', '5008', '5008'),
    ('peugeot', 'Partner', 'partner'),
    ('peugeot', 'Expert', 'expert'),
    ('peugeot', 'Boxer', 'boxer'),
    ('peugeot', 'Landtrek', 'landtrek'),
    -- Porsche
    ('porsche', '911', '911'),
    ('porsche', 'Macan', 'macan'),
    ('porsche', 'Cayenne', 'cayenne'),
    ('porsche', 'Panamera', 'panamera'),
    -- Ram
    ('ram', 'Rampage', 'rampage'),
    ('ram', 'Dakota', 'dakota'),
    ('ram', '1500', '1500'),
    ('ram', '2500', '2500'),
    -- Renault
    ('renault', 'Twingo', 'twingo'),
    ('renault', 'Kwid', 'kwid'),
    ('renault', 'Clio', 'clio'),
    ('renault', 'Sandero', 'sandero'),
    ('renault', 'Sandero Stepway', 'sandero-stepway'),
    ('renault', 'Logan', 'logan'),
    ('renault', 'Symbol', 'symbol'),
    ('renault', 'Mégane', 'megane'),
    ('renault', 'Fluence', 'fluence'),
    ('renault', 'Scénic', 'scenic'),
    ('renault', 'Captur', 'captur'),
    ('renault', 'Duster', 'duster'),
    ('renault', 'Kardian', 'kardian'),
    ('renault', 'Koleos', 'koleos'),
    ('renault', 'Duster Oroch', 'duster-oroch'),
    ('renault', 'Alaskan', 'alaskan'),
    ('renault', 'Kangoo', 'kangoo'),
    ('renault', 'Master', 'master'),
    -- Subaru
    ('subaru', 'Impreza', 'impreza'),
    ('subaru', 'XV', 'xv'),
    ('subaru', 'Forester', 'forester'),
    ('subaru', 'Outback', 'outback'),
    -- Suzuki
    ('suzuki', 'Fun', 'fun'),
    ('suzuki', 'Swift', 'swift'),
    ('suzuki', 'Baleno', 'baleno'),
    ('suzuki', 'Jimny', 'jimny'),
    ('suzuki', 'Vitara', 'vitara'),
    ('suzuki', 'Grand Vitara', 'grand-vitara'),
    ('suzuki', 'S-Cross', 's-cross'),
    -- Toyota
    ('toyota', 'Etios', 'etios'),
    ('toyota', 'Yaris', 'yaris'),
    ('toyota', 'Corolla', 'corolla'),
    ('toyota', 'Prius', 'prius'),
    ('toyota', 'Camry', 'camry'),
    ('toyota', 'Corolla Cross', 'corolla-cross'),
    ('toyota', 'C-HR', 'c-hr'),
    ('toyota', 'RAV4', 'rav4'),
    ('toyota', 'SW4', 'sw4'),
    ('toyota', 'Land Cruiser', 'land-cruiser'),
    ('toyota', 'Hilux', 'hilux'),
    ('toyota', 'Hiace', 'hiace'),
    -- Volkswagen
    ('volkswagen', 'Up!', 'up'),
    ('volkswagen', 'Gol', 'gol'),
    ('volkswagen', 'Gol Trend', 'gol-trend'),
    ('volkswagen', 'Fox', 'fox'),
    ('volkswagen', 'CrossFox', 'crossfox'),
    ('volkswagen', 'Suran', 'suran'),
    ('volkswagen', 'Voyage', 'voyage'),
    ('volkswagen', 'Polo', 'polo'),
    ('volkswagen', 'Virtus', 'virtus'),
    ('volkswagen', 'Bora', 'bora'),
    ('volkswagen', 'Vento', 'vento'),
    ('volkswagen', 'Golf', 'golf'),
    ('volkswagen', 'Passat', 'passat'),
    ('volkswagen', 'Scirocco', 'scirocco'),
    ('volkswagen', 'Nivus', 'nivus'),
    ('volkswagen', 'T-Cross', 't-cross'),
    ('volkswagen', 'Taos', 'taos'),
    ('volkswagen', 'Tiguan', 'tiguan'),
    ('volkswagen', 'Tiguan Allspace', 'tiguan-allspace'),
    ('volkswagen', 'Touareg', 'touareg'),
    ('volkswagen', 'Sharan', 'sharan'),
    ('volkswagen', 'Saveiro', 'saveiro'),
    ('volkswagen', 'Amarok', 'amarok'),
    -- Volvo
    ('volvo', 'V40', 'v40'),
    ('volvo', 'S60', 's60'),
    ('volvo', 'EX30', 'ex30'),
    ('volvo', 'XC40', 'xc40'),
    ('volvo', 'XC60', 'xc60'),
    ('volvo', 'XC90', 'xc90')
) AS v (marca_slug, nombre, slug)
JOIN marca ON marca.slug = v.marca_slug
ON CONFLICT DO NOTHING;
